### ISSUE TITLE
After EMAIL received!

### ISSUE THREAD

**Issue by AR-Coding-126** [tinycoder2/FaceFind#2]
The main goal of the project is to find the missing person, but the main purpose of the project is not achieved. The project only matches the reported person with the missing person's list and if found, sends an email to their guardian. The email shows the guardian’s name, the missing person’s name, location, and time. But what happens if the location is Delhi? Delhi is a very crowded and big city. How can you find the missing person if you only know the location is Delhi?
![image](https://github.com/tinycoder2/FaceFind/assets/100079496/d7b7ba3e-2d3a-4c07-90ef-4da8c1897d30)

**Comment by tinycoder2** [comment]
Hi Aqib Raza, As mentioned in the future works section, one could enhance the current implementation by capturing the GPS location of the volunteer who reports a sighting instead of relying solely on textual information. The project can help assist authorities in identifying potential leads for locating the missing person. Hope this helps, cheers!
